-- Punto 1: Consulta del supermercado con más cantidad de productos de tipo "CARNICOS" vendidos hasta el 31 de diciembre de 2013.
SELECT 
    S.NOMBRE_SUPERMERCADO AS NombreSupermercado,
    COUNT(F.NUMERO_FACTURA) AS Cantidad,
    TP.DESCRIPCION_TIPO AS TipoSupermercado,
    F.FECHA_VENTE AS FechaVenta
FROM
    FACTURA F
INNER JOIN VENDEDOR V ON F.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN SUPERMERCADO S ON V.ID_SUPERMERCADO = S.ID_SUPERMERCADO
INNER JOIN PRODUCTO P ON F.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN TIPO_PRODUCTO TP ON P.ID_TIPO_PRODUCTO = TP.ID_TIPO_PRODUCTO
WHERE
    TP.DESCRIPCION_TIPO = 'Carnicos'
    AND F.FECHA_VENTE <= '2013-12-31'
GROUP BY
    S.NOMBRE_SUPERMERCADO, TP.DESCRIPCION_TIPO
ORDER BY
    COUNT(F.NUMERO_FACTURA) DESC
LIMIT 1;

-- Punto 2: Clientes que compran en "Exito" y cuya compra supera los $150.000 pesos.
SELECT 
    C.*,
    S.NOMBRE_SUPERMERCADO AS NombreSupermercado,
    F.VALOR_VENTA AS ValorVenta
FROM
    FACTURA F
INNER JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN VENDEDOR V ON F.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN SUPERMERCADO S ON V.ID_SUPERMERCADO = S.ID_SUPERMERCADO
WHERE
    S.NOMBRE_SUPERMERCADO = 'Exito'
    AND F.VALOR_VENTA > 150000
ORDER BY
    F.VALOR_VENTA DESC;

-- Punto 3: Ventas totales de cada vendedor en cada supermercado.
SELECT 
    V.NOMBRE_VENDEDOR AS NombreVendedor,
    S.NOMBRE_SUPERMERCADO AS NombreSupermercado,
    SUM(F.VALOR_VENTA) AS TotalVentas
FROM
    FACTURA F
INNER JOIN VENDEDOR V ON F.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN SUPERMERCADO S ON V.ID_SUPERMERCADO = S.ID_SUPERMERCADO
GROUP BY
    V.NOMBRE_VENDEDOR, S.NOMBRE_SUPERMERCADO
ORDER BY
    SUM(F.VALOR_VENTA) DESC;

-- Punto 4: Facturas con valor superior a $100.000 pesos y código de vendedor igual a 3.
SELECT 
    F.NUMERO_FACTURA AS NumeroFactura,
    F.VALOR_VENTA AS ValorFactura,
    V.NOMBRE_VENDEDOR AS NombreVendedor
FROM
    FACTURA F
INNER JOIN VENDEDOR V ON F.ID_VENDEDOR = V.ID_VENDEDOR
WHERE
    F.VALOR_VENTA > 100000
    AND V.ID_VENDEDOR = 3;
